# Generated by Django 3.0.2 on 2020-03-08 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('display_name', models.CharField(max_length=30, unique=True)),
                ('twitter_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_a', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_b', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.IntegerField(default=38)),
                ('reversevideo', models.BooleanField(default=False)),
                ('datecolor', models.CharField(default='black', max_length=20)),
                ('detailcolor', models.CharField(default='#0000C0', max_length=20)),
                ('attendeescolor', models.CharField(default='#00C000', max_length=20)),
                ('backgroundcolor', models.CharField(default='#F3FFF3', max_length=20)),
                ('datecolor_rev', models.CharField(default='white', max_length=20)),
                ('detailcolor_rev', models.CharField(default='aqua', max_length=20)),
                ('attendeescolor_rev', models.CharField(default='lawngreen', max_length=20)),
                ('backgroundcolor_rev', models.CharField(default='black', max_length=20)),
                ('photo_cover', models.ImageField(null=True, upload_to='images/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('logged_in', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('last_visited', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=20)),
                ('sent_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('is_live_sender', models.BooleanField(default=True)),
                ('is_live_recipient', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['received_date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=40, null=True, unique=True)),
                ('display_name', models.CharField(max_length=30, unique=True)),
                ('authorname', models.CharField(blank=True, max_length=20, null=True)),
                ('meetup_name', models.CharField(blank=True, max_length=40, null=True)),
                ('twitter_name', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_a', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_b', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('fullmember', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=20)),
                ('reversevideo', models.BooleanField(default=False)),
                ('datecolor', models.CharField(default='black', max_length=20)),
                ('detailcolor', models.CharField(default='#0000C0', max_length=20)),
                ('attendeescolor', models.CharField(default='#00C000', max_length=20)),
                ('backgroundcolor', models.CharField(default='#F3FFF3', max_length=20)),
                ('datecolor_rev', models.CharField(default='white', max_length=20)),
                ('detailcolor_rev', models.CharField(default='aqua', max_length=20)),
                ('attendeescolor_rev', models.CharField(default='lawngreen', max_length=20)),
                ('backgroundcolor_rev', models.CharField(default='black', max_length=20)),
                ('photo_cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('logged_in', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('last_visited', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('branches', models.ManyToManyField(to='users.Branch')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
