# Generated by Django 3.0.2 on 2020-03-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_date']},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='photo_cover',
            new_name='cover',
        ),
    ]
