# Generated by Django 3.0.2 on 2020-03-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200311_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='logged_in',
        ),
    ]
