# Generated by Django 3.0.2 on 2020-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_branch_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='branches',
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_a',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_b',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(8, 'Contact'), (15, 'Prospective'), (20, 'Member'), (30, 'Planner'), (35, 'Introducer'), (40, 'Committee'), (50, 'Treasurer'), (60, 'Admin')], default=15),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
