# Generated by Django 3.0.2 on 2020-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200312_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(8, 'Contact'), (10, 'Public'), (15, 'Prospective'), (20, 'Member'), (30, 'Planner'), (35, 'Introducer'), (40, 'Committee'), (50, 'Treasurer'), (55, 'WebManager'), (60, 'Admin')], default=15),
        ),
    ]
