# Generated by Django 3.0.2 on 2020-03-21 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(blank=True, default='', null=True, verbose_name='Notice')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorn', to='users.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of the event, in the format "dd/mm/yy", e.g. for 31st December 2020, enter "31/12/20"')),
                ('detail_public', models.CharField(blank=True, default='', max_length=80, verbose_name='Title of event, this be shown publicly')),
                ('detail_private', models.TextField(blank=True, null=True, verbose_name='Details of event')),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_live', models.BooleanField(default=True)),
                ('editable', models.BooleanField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='bookedin2', to='users.Person')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hosts', models.ManyToManyField(blank=True, related_name='hh2', to='users.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(blank=True, default='', null=True, verbose_name='Notice')),
                ('amendment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authora', to='users.Person')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventa', to='events.Event')),
            ],
        ),
    ]
