# Generated by Django 3.0.2 on 2020-03-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='editable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
