# Generated by Django 3.0.2 on 2020-03-21 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_site', models.BooleanField(default=True)),
                ('daily', models.BooleanField(default=False)),
                ('club', models.BooleanField(default=True)),
                ('criterion4', models.BooleanField(default=True)),
                ('criterion5', models.BooleanField(default=True)),
                ('criterion6', models.BooleanField(default=True)),
                ('advert', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=True)),
                ('content', models.TextField(null=True)),
                ('sent_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorq', to='users.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100)),
                ('is_live', models.BooleanField(default=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('editable', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorp', to='users.Person')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=100)),
                ('is_live', models.BooleanField(default=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authory', to='users.Person')),
            ],
        ),
    ]
