# Generated by Django 3.0.2 on 2020-03-11 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=True)),
                ('content', models.TextField(null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='photo_cover',
            new_name='cover',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='attendeescolor_rev',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='backgroundcolor_rev',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='datecolor_rev',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='detailcolor_rev',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='reversevideo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='status',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=True)),
                ('content', models.TextField(null=True)),
                ('sent_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorq', to='users.Person')),
            ],
        ),
    ]
