# Generated by Django 3.0.2 on 2020-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200311_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
