# Generated by Django 3.0.2 on 2020-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200312_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_site', models.BooleanField(default=True)),
                ('advert', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Sitesettings',
        ),
        migrations.AlterField(
            model_name='photo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
