# Generated by Django 3.0.2 on 2020-03-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200313_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
